# Site settings
title: James T Farrington
email: JamesTFarrington@gmail.com
description: "This is the personal blog of James Farrington."
baseurl: ""
url: ""
github_username:  JamesTFarrington

# Build settings
markdown: kramdown
permalink: pretty
